### ISSUE TITLE
Session 5: Commands/Scripts to add custom visas to the broker

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/ismb-2022-ga4gh-tutorial#13]
For session 5, each CRAM file will be controlled by 1 of 5 visas. Each visa represents access control to a "super population" of 1000 genomes individuals (East Asian, South Asian, American, African, European ancestry). e.g. Researchers that want to access CRAMs of American individuals will need the "American dataset" visa.

After Passport service start up, these 5 visas will need to be added to the broker, either as a Python script or 5 POST requests visa postman.

Here is the info for each Visa:
1. East Asian
    * visaName: `1000GenomesIndividualsWithEastAsianAncestry` 
    * visaIssuer: `https://federatedgenomics.org/`
    * visaDescription: Controls access to genomic data obtained from individuals with East Asian ancestry
    * visaSecret: `29CD6DFBB2684BAEACED3B1C6A7F4`
2. European:
    * visaName: `1000GenomesIndividualsWithEuropeanAncestry` 
    * visaIssuer: `https://federatedgenomics.org/`
    * visaDescription: Controls access to genomic data obtained from individuals with European ancestry
    * visaSecret: `47B42DF32976DFDBD6EC4D9ED2593`
3. African:
    * visaName: `1000GenomesIndividualsWithAfricanAncestry` 
    * visaIssuer: `https://federatedgenomics.org/`
    * visaDescription: Controls access to genomic data obtained from individuals with African ancestry
    * visaSecret: `582A164E2C5DA377F3E3F76158CE6`
4. American:
    * visaName: `1000GenomesIndividualsWithAmericanAncestry` 
    * visaIssuer: `https://federatedgenomics.org/`
    * visaDescription: Controls access to genomic data obtained from individuals with American ancestry
    * visaSecret: `BF9CAB5D5157C5C21EBDEE6C91D91`
5. South Asian:
    * visaName: `1000GenomesIndividualsWithSouthAsianAncestry` 
    * visaIssuer: `https://federatedgenomics.org/`
    * visaDescription: Controls access to genomic data obtained from individuals with South Asian ancestry
    * visaSecret: `9474C832599DC95F949DB3CAE443E`

[Reference](https://github.com/ga4gh/ismb-2022-ga4gh-tutorial/blob/main/sessions/5/scripts/add-known-visas-to-drs.py)

@emre-f @Chen2x

**Comment by emre-f** [comment]
Added instructions using Postman to be able to add all the visas.
