### ISSUE TITLE
Clarifications for session 5

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/ismb-2022-ga4gh-tutorial#16]
1. After requesting `/search` on data connect server which provides the Drs uri for cram, crai, and bundle, what is the next step? Do we take these URI's and go to Drs server? 
2. How is the Drs URI resolved to an accessible s3 URL? Is there an endpoint that does this or are we manually doing the resolution?
3. What is the Drs endpoint that gives the information about passport brokers and required visas?
4. How can I remove the default test visas (StarterKitDatasetsControlledAccessGrants, DatasetAlpha, DatasetBeta, DatasetGamma) available in the Passport broker? 
5. What is the Header field name for adding passport jwt to Drs request? Can you provide an example request?
6. Does running `python3 scripts/add-known-visas-to-drs.py` and `python3 scripts/populate-drs.py` add the 1000 genome sample population-based visa information and 1000 genome sample data to Drs server? Is there a correct sequence to run these 2 scripts?
7. What is the conclusion step of session 5? Does it end with the Drs returning the s3 URL for the requested Drs object and the participant being able to access this s3 URL to download a file?
8. Since, we use DRS in both session 4 and session 5, and only the Drs in session 5 uses passports for authorization. How is this configured?
9. For the data connect 1000 genomes table, we took a subset based on the rules below, which resulted in 200 rows -
```
2 unique records in sex
{'male', 'female'}

26 unique records in population_code
{'ITU', 'ASW', 'JPT', 'MSL', 'CHS', 'CDX', 'YRI', 'ACB', 'MXL', 'PUR', 'FIN', 'GWD', 'LWK', 'GIH', 'CLM', 'TSI', 'PEL', 'PJL', 'GBR', 'CHB', 'BEB', 'ESN', 'KHV', 'CEU', 'IBS', 'STU'}

30 unique records in population_name
{'Bengali,Bengali', 'African Ancestry SW', 'Punjabi', 'Dai Chinese', 'Gambian Mandinka', 'Yoruba', 'British', 'Japanese', 'Iberian', 'African Caribbean', 'Mende', 'Southern Han Chinese', 'Han Chinese', 'Luhya', 'Kinh,Kinh Vietnamese', 'Toscani', 'Luhya,Luhya', 'Kinh Vietnamese', 'Tamil', 'Gujarati', 'Bengali', 'Finnish', 'CEPH', 'Telugu', 'Peruvian', 'Esan', 'Colombian', 'Punjabi,Punjabi', 'Puerto Rican', 'Mexican Ancestry'}

5 unique records in superpopulation_code
{'AMR', 'EAS', 'EUR', 'SAS', 'AFR'}

8 unique records in superpopulation_name
{'East Asian Ancestry', 'European Ancestry', 'African Ancestry', 'American Ancestry', 'East Asia (SGDP),East Asian Ancestry', 'South Asian Ancestry', 'South Asia (SGDP),South Asian Ancestry', 'African Ancestry,Africa (SGDP)'}

```
I see that the Drs database has 46 rows of 1000 genome samples in it. Is there a different set of rules that were used to obtain this subset? If yes, then let me know the rules used, so I will make sure that data connect uses the same subset.

Hi @jb-adams. I have a few questions regarding session 5. Would appreciate your help with these. Thank you!!

**Comment by ianfore** [comment]
Answers to some of the questions below.
1. After requesting `/search` on data connect server which provides the Drs uri for cram, crai, and bundle, what is the next step? Do we take these URI's and go to Drs server? 
_Yes_
3. How is the Drs URI resolved to an accessible s3 URL?
- _Either_
-- _build the drs end point from the host name_
-- r_esolve the drs prefix_
- **Call <end_point>/objects<drs_id>/access/<access_id>**
-- include authentication if needed_
5. What is the Drs endpoint that gives the information about passport brokers and required visas?
- _Still under development_
 - _Check with Jeremy_
9. What is the conclusion step of session 5? Does it end with the Drs returning the s3 URL for the requested Drs object and the participant being able to access this s3 URL to download a file?
- _Passing it to a WES service_
- _Suggest not downloading the file. The whole point is to compute on it in place_

_All of the above are illustrated in many of the fast-scripts notebooks.
A good example is in https://github.com/ga4gh/fasp-scripts/blob/master/notebooks/FASPNotebook18-GTEXExample-AWS.ipynb
You would have to look at the clients in the fasp-scripts repo to see the underlying REST API calls._

**Comment by yash-puligundla** [comment]
Thank you @ianfore

**Comment by ianfore** [comment]
@yash-puligundla you'll find that identifiers.org will not only resolve the identifier prefix, but also redirect you straight to the DRS /objects response.
so you would take drs://dg.4dfc:098e18d4-5ece-4bc6-9a79-68f5082da9bc fro above and use identifiers.org as follows:
https://identifiers.org/dg.4dfc:098e18d4-5ece-4bc6-9a79-68f5082da9bc

**Comment by yash-puligundla** [comment]
> @yash-puligundla you'll find that identifiers.org will not only resolve the identifier prefix, but also redirect you straight to the DRS /objects response. so you would take the drs://dg.4dfc:098e18d4-5ece-4bc6-9a79-68f5082da9bc example above and use identifiers.org as follows: https://identifiers.org/dg.4dfc:098e18d4-5ece-4bc6-9a79-68f5082da9bc
> 
> That behavior is down to the way that Michael, Binam and/or their colleagues registered the prefix with identifiers.org. The url_pattern is the thing that does it. The relevant details are shown on this page https://registry.identifiers.org/registry/dg.4dfc#! Other DRS servers would do the same.

This is good to know. Thank you, Ian. But, I doubt if this is the case with the starter kit. "https://identifiers.org/HG00284.1kgenomes.wgs.downsampled.bundle" is invalid, which makes me think it is not registered with identifiers.org. 

I believe we can use the first option you listed above

> a) for a host based URI, build the drs end point from the host name
> --- e.g. for drs://nci-crdc.datacommons.io/098e18d4-5ece-4bc6-9a79-68f5082da9bc
> --- the DRS endpoint would be https://nci-crdc.datacommons.io/ga4gh/drs/v1

Here is an example drs uri from data connect: "drs://localhost:5000/HG00284.1kgenomes.wgs.downsampled.bundle"
In this example, I am not sure how I would get the drs object id from this uri

Is the drs object id = "HG00284.1kgenomes.wgs.downsampled.bundle" or is there a UUID that I need to obtain from somewhere? (I think this might be very specific to the starter kit implementation)

**Comment by ianfore** [comment]
Just posted [this](https://github.com/ga4gh/ismb-2022-ga4gh-tutorial/issues/17) as a separate issue. Then I saw your last paragraph. The new issue essentially addresses what you ask. I wanted to separate the id issue from the resolution issue.

Back to resolution. No, identifiers.org knows nothing about your local host. 

Prefix based DRS ids are a good thing though, 

- Run DRSMetaResolver locally. At the moment though it's just a python module and not a callable service. Probably not hard to turn it into a service, but I don't think we should take that on at this point.
- There is a prefix resolver service that could be run locally. It will try and resolve locally anything that identifiers.org doesn't know about. I've been meaning to check it out anyway. This is a good reason to do so.

Watch this space!

**Comment by ianfore** [comment]
The prefix resolver that I understood could be run locally is Bioregistry.
First off though, note that it can be used in the same way as identifiers.org.
https:/bioregistry.io/dg.4dfc:098e18d4-5ece-4bc6-9a79-68f5082da9bc
Same DRS id and prefix as above - different metaresolver.

**Running Bioregistry locally**
See https://github.com/ga4gh/ismb-2022-ga4gh-tutorial/tree/main/supporting/bioregistry

**Comment by yash-puligundla** [comment]
Hi @jb-adams 
I am trying to change the passport issuer from "https://ga4gh.org/" to something else. I wanted to check with you if I can use a config file for the passport-broker container to do this. 

Here is the config.yaml file, but it doesn't work as expected. 

```
passport-broker:
  brokerProps:
    passportIssuer: http://localhost:4455/
```
Can you please take a look and see if I am doing something incorrectly? Thanks!

**Comment by yash-puligundla** [comment]
I was able to figure out the error in the config file. Closing this issue as session 5 content is good to go!! Thank you, Ian and Jeremy!
