### ISSUE TITLE
Session 4 - DRS setup and exploration

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/ismb-2022-ga4gh-tutorial#2]
Add tutorial steps for DRS setup and exploration phase of the tutorial during session 4. Steps include 

- Download and install DRS image (docker compose)
- Populate DRS database with DRS Objects scoped to the tutorial
- Make requests to the following endpoints:
  * service info
  * get object (phenopackets, 1k genomes, bundles, blobs, expand=true/false)
  * batch request of above data

**Comment by Chen2x** [comment]
Hello @jb-adams, hope you are doing well at your new job! While working through session 4 I noticed the script ```scripts/create_1000genomes_drs_dataset.py``` that was defined in the readme does not currently exist in that directory. Has this file been misplaced or will it need to be written?

**Comment by ianfore** [comment]
@Chen2x @jb-adams . Am wondering if the create_1000genomes_drs_dataset.py file is relevant to the creation of the one_thousand_genomes_sample Data Connect table. If so I'd be interested to see the file. It may help me with #17 and the branch associated with it.
