### ISSUE TITLE
Session 4 - WES setup and workflow execution 

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/ismb-2022-ga4gh-tutorial#3]
Steps to setup WES and make workflow run requests. Steps include

- deploy WES instance (part of docker compose)
- Service info endpoint
- Run/monitor "hello world" workflows in both Nextflow and WDL
- Run/monitor CNest workflow in both Nextflow and WDL

**Comment by yash-puligundla** [comment]
Hi @jb-adams , Where can I find the CNest nextflow and wdl scripts?

**Comment by ianfore** [comment]
@yash-puligundla - this is what I've worked from https://github.com/tf2/CNest

**Comment by ianfore** [comment]
Added my CNest WES Script. See 2/notebooks/SBCGC Running CNest.ipynb
