### ISSUE TITLE
Data Connect query only fails

### ISSUE THREAD

**Issue by ianfore** [ga4gh/ismb-2022-ga4gh-tutorial#30]
The following is a non-parameterized alternate to the example query in the Part 2 readme.
It is still a legal Data Connect query, but it fails.
```
{
  "query": "select sample_name , sex , population_code , population_name, cram_drs_uri, crai_drs_uri, bundle_drs_uri from one_thousand_genomes_sample where population_code='PUR' and sex='female';"
} 
```

Error as follows:
```
{
    "timestamp": "2022-06-21T11:37:30.080+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/search"
}
```

**Comment by ianfore** [comment]
Thanks @yash-puligundla . Yes it runs with an empty parameters array. OKas a workaround. However, in the [spec here](https://github.com/ga4gh-discovery/data-connect/blob/develop/SPEC.md) parameters is optional.

**Comment by yash-puligundla** [comment]
Agreed. I have opened an [issue](https://github.com/ga4gh/ga4gh-starter-kit-data-connect/issues/24) on the Starter Kit Data Connect repo.

**Comment by ianfore** [comment]
Closing for the tutorial. Let's leave it with the issue on the Starter Kit Data Connect repo.

We can workaround for the tutorial.
