### ISSUE TITLE
Issue encountered using FASP package in Jupyter

### ISSUE THREAD

**Issue by ianfore** [ga4gh/ismb-2022-ga4gh-tutorial#31]
On 6/20 we had trouble using the fasp package from Jupyter on @yash-puligundla 's machine.

Yash are you able to paste in the log that showed up in terminal when you started Jupyter?

I tested the install on a clean python environment on a different machine from my regular one. It all worked OK. Once the python virtual environment was activated, and jupyter notebook was started from that environment everything worked OK.

I have a Windows VM available and will test on there if I have time. Or is anyone else available to test on Windows?

**Comment by yash-puligundla** [comment]
Hi @ianfore. This is the log I see when I start a jupyter notebook from a venv

> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
>   return _iterencode(o, 0)

The following is after I run `import fasp`

> ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fa215f67340>(<Future finis...79c"\r\n\r\n'>)
> handle: <Handle <TaskWakeupMethWrapper object at 0x7fa215f67340>(<Future finis...79c"\r\n\r\n'>)>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
> RuntimeError: Cannot enter into task <Task pending name='Task-1' coro=<HTTP1ServerConnection._server_request_loop() running at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...579c"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_client/manager.py:335>> is being executed.
> ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fa215ef2ac0>(<Future finis...79c"\r\n\r\n'>)
> handle: <Handle <TaskWakeupMethWrapper object at 0x7fa215ef2ac0>(<Future finis...79c"\r\n\r\n'>)>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
> RuntimeError: Cannot enter into task <Task pending name='Task-2' coro=<HTTP1ServerConnection._server_request_loop() running at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...579c"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_client/manager.py:336>> is being executed.
> [I 09:50:30.036 NotebookApp] Kernel started: dea27323-18a7-4642-ba3d-28371e44107b, name: ismb_venv
> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
>   return _iterencode(o, 0)
