### ISSUE TITLE
Docker desktop link on sessions starterkit readme points to docker compose

### ISSUE THREAD

**Issue by ianfore** [ga4gh/ismb-2022-ga4gh-tutorial#34]
It should point to https://www.docker.com/products/docker-desktop/

Also note that installing docker desktop installs docker compose.
See second section here https://docs.docker.com/get-started/08_using_compose/
So the second line to install Docker compose is not be necessary.

**Comment by yash-puligundla** [comment]
Thanks Ian. They are fixed.

**Comment by yash-puligundla** [comment]
This is wonderful. Thank you, Ian. I will add virtual env to the list. 

> Docker desktop was a bit tricky - it didn't run right first time. I had to run an update of WSL which Docker depends on.

Did you happen to capture the error/behavior when you tried to install docker desktop?

**Comment by ianfore** [comment]
> Did you happen to capture the error/behavior when you tried to install docker desktop?

'fraid not. :-)
The install itself went OK.
When I ran Docker Desktop it gave me an error and a link to go to update WSL.

**Comment by ianfore** [comment]
I also ran through installing things for sessions/2 on top of what was set up for the Starter Kit sessions. It ran OK. Details as follows.

```
(ismbtest) C:\Users\<user>\fasp-scripts>pip install jupyter
(ismbtest) C:\Users\<user>\fasp-scripts>pip install .
(ismbtest) C:\Users\<user>\fasp-scripts>cd ..\ismb-2022-ga4gh-tutorial\sessions\2
(ismbtest) C:\Users\<user>\fasp-scripts> jupyter notebook
```

Thanks for your logs in issue #31 . I haven't tried to debug that yet. Can someone else try session 2 to see if they get the same problem? We may have to come back to your machine to sort the specific issues, but it would be good to get a sense whether it is a universal problem or not by trying it one someone else's machine.

**Comment by yash-puligundla** [comment]
> When I ran Docker Desktop it gave me an error and a link to go to update WSL.

Good to know. As long as the error is not cryptic, we should be fine.

> Thanks for your logs in issue https://github.com/ga4gh/ismb-2022-ga4gh-tutorial/issues/31 . I haven't tried to debug that yet. Can someone else try session 2 to see if they get the same problem? We may have to come back to your machine to sort the specific issues, but it would be good to get a sense whether it is a universal problem or not by trying it one someone else's machine.

Glad to hear it works fine on your machine. I didn't get a chance to debug either. But, hoping that it's specific to my machine.

I have added create & activate venv steps to SETUP.md. We can add the specific pip install commands at the start of each of our tutorials.

**Comment by yash-puligundla** [comment]
removed setup.md to avoid duplication of instructions. Pointing to [this document](https://docs.google.com/document/d/1n3UjQ1m0B1fG3LHFDPXx1OUw2uMzms5uANK76cngDyc/edit?usp=sharing) instead.
