### ISSUE TITLE
Add Environment Set up instructions for sessions 2 and 3

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/ismb-2022-ga4gh-tutorial#38]
Hi @ianfore Can you please add setup instructions for sessions 2 and 3 to this [wiki page](https://github.com/ga4gh/ismb-2022-ga4gh-tutorial/wiki/Environment-Set-Up-Instructions)? Once, we are ready we can send it to Steven, so he can circulate it to the participants. 

Sorry, but I just noticed that the deadline is on June 29. Let me know if you would like my help with this.

**Comment by ianfore** [comment]
I was had Jun 30 in my head, latest deadline I saw (from Annette). Was waiting on the results of the dry run before sending.

Do we want to circulate the whole repo? I was thinking people would only get that on the day. Beforehand I was thinking they just get the list of things to have ready.

Susan requested an account from CGC, and you had done so already. Did Chen, Alex, Emre or Fabio. One of the things we need to check before sending out the instructions to attendees is that the use of CGC works as planned.

**Comment by yash-puligundla** [comment]
June 30th is the deadline for presentation materials and June 29th is for the set up instructions that will be circulated to the participants.

Let's email Steven for an extension of the deadline. That way we can be sure of the steps before they are sent out.
